### ISSUE TITLE
make package compatible with EDI's congruence checker

### ISSUE THREAD

**Issue by thesadie** [CVPIA-OSC/EDIutils#12]
Write tests, warnings, and errors for each function that covers what EDI's checker does

[EDI's congruence checker github repos](https://github.com/EDIorg/ECC)
[spreadsheet of checks](https://docs.google.com/spreadsheets/d/14r-74onIKdq2oUmn5U7itX5bfBkfJ16_BhaqTEaul74/edit#gid=0)

**Comment by ErinCain** [comment]
I am able to generate a working EML document to submit to EDI.
