### ISSUE TITLE
Add try_catch to EMLaide api functions to replace the if break statements

### ISSUE THREAD

**Issue by ErinCain** [CVPIA-OSC/EDIutils#159]

**Comment by alvizek** [comment]
When running api functions through automated workflow function returns message (even if package didn't upload) so difficult to tell when the github action was successful. 

Need to add some sort of stop so that know when package not uploaded.

**Comment by alvizek** [comment]
I changed `message` to `stop` for all situations in the api functions where we wanted the function to error out and print message.

**Comment by alvizek** [comment]
inigo is going to make these changes to the `evaluate` function as well.
