### ISSUE TITLE
create function to read workbook metadata 

### ISSUE THREAD

**Issue by ergz** [CVPIA-OSC/EDIutils#41]
currently we keep calling read_xlsx to read different sheets from the workbook, once we have decided what needs to be kept in the workbook we should implement a function that reads the entire workbook at once, this data structure will then be called by each of the `add_*` functions

Proposed: 

```r
metadata <- edi_read_workbook("path_to_workbook.xlsx")

# return the dataframe needed by the add_license function
metadata$license
```

**Comment by ErinCain** [comment]
Added this as part of the workflow on vignette!
