### ISSUE TITLE
add defaults for funding element

### ISSUE THREAD

**Issue by thesadie** [CVPIA-OSC/EDIutils#43]
for funder ID in our EDIutils package we can use the wikidata urls
the majority of projects the funder is USBR:
USBR - https://www.wikidata.org/wiki/Q1010548

Sometimes there are contributions from state funds:
CDWR - https://www.wikidata.org/wiki/Q5020440
CDFW - https://www.wikidata.org/wiki/Q5020421

please investigate schema for multiple funders in [structured funding information](https://nceas.github.io/eml/whats-new-in-eml-2-2-0.html#structured-funding-information)

make any necessary updates to template workbook and instructions based on what you find out

**Comment by ErinCain** [comment]
I will take over this task.

**Comment by ErinCain** [comment]
I have a couple ideas on how to do default funding. It depends on how many details we want to add on to each funding source. I will check with Sadie to decide on this in the next couple of days.
